"""typed_business_domains_and_shared_approvals"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '2892f6fa2482'
down_revision = '0a4d2ae24887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('rule_key', sa.String(length=80), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('mold',
    sa.Column('internal_number', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('internal_number')
    )
    op.create_table('supplier',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('warehouse',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('scope_confirmed', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('opening_evidence', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('business_subject',
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('number', sa.String(length=80), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('warehouse_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('round_no', sa.Integer(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','SUBMITTED','APPROVED','REJECTED','RETURNED','APPLY_BLOCKED','EFFECTIVE','CANCELLED','CLOSED')", name='subject_status'),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_business_subject_kind'), 'business_subject', ['kind'], unique=False)
    op.create_index(op.f('ix_business_subject_project_id'), 'business_subject', ['project_id'], unique=False)
    op.create_table('project_mold',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('mold_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mold_id'], ['mold.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'mold_id')
    )
    op.create_table('project_profile',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('execution_mode', sa.String(length=30), nullable=False),
    sa.Column('customer_due_date', sa.Date(), nullable=True),
    sa.Column('settlement_status', sa.String(length=30), nullable=False),
    sa.CheckConstraint("execution_mode IN ('INTERNAL','FULL_OUTSOURCE')"),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('risk_analysis_result',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('authorization_hash', sa.String(length=64), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.Column('findings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('limitations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_policy',
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('near_due_days', sa.Integer(), nullable=False),
    sa.Column('configured_by', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('near_due_days BETWEEN 0 AND 90'),
    sa.ForeignKeyConstraint(['configured_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('stock_balance',
    sa.Column('warehouse_id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity >= 0'),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'material_id', 'project_id')
    )
    op.create_table('business_decision_detail',
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('source_subject_id', sa.String(length=36), nullable=True),
    sa.Column('decision', sa.String(length=40), nullable=False),
    sa.Column('execution_mode', sa.String(length=30), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['source_subject_id'], ['business_subject.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['business_subject.id'], ),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_table('contract_detail',
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('supplier_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('contract_number', sa.String(length=100), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('replaces_id', sa.String(length=36), nullable=True),
    sa.CheckConstraint('amount > 0'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['replaces_id'], ['business_subject.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['business_subject.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_table('engineering_change_detail',
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('problem', sa.Text(), nullable=False),
    sa.Column('solution', sa.Text(), nullable=False),
    sa.Column('customer_due_affected', sa.Boolean(), nullable=False),
    sa.Column('customer_evidence', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['business_subject.id'], ),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_table('pause_record',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('resume_subject_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['resume_subject_id'], ['business_subject.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['business_subject.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_subject_id'),
    sa.UniqueConstraint('subject_id')
    )
    op.create_index(op.f('ix_pause_record_project_id'), 'pause_record', ['project_id'], unique=False)
    op.create_table('payment_confirmation',
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('confirmed_by', sa.String(length=36), nullable=False),
    sa.Column('reversal_of_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount <> 0'),
    sa.ForeignKeyConstraint(['confirmed_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['business_subject.id'], ),
    sa.ForeignKeyConstraint(['reversal_of_id'], ['payment_confirmation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference'),
    sa.UniqueConstraint('reversal_of_id')
    )
    op.create_index(op.f('ix_payment_confirmation_request_id'), 'payment_confirmation', ['request_id'], unique=False)
    op.create_table('payment_stage',
    sa.Column('contract_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('condition', sa.Text(), nullable=False),
    sa.Column('condition_confirmed', sa.Boolean(), nullable=False),
    sa.Column('condition_evidence', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0'),
    sa.ForeignKeyConstraint(['contract_id'], ['business_subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_detail',
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('previous_id', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['previous_id'], ['business_subject.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['business_subject.id'], ),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_table('plan_task',
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('planned_start', sa.Date(), nullable=False),
    sa.Column('planned_end', sa.Date(), nullable=False),
    sa.Column('actual_start', sa.Date(), nullable=True),
    sa.Column('actual_end', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('planned_end >= planned_start'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['business_subject.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'key')
    )
    op.create_index(op.f('ix_plan_task_plan_id'), 'plan_task', ['plan_id'], unique=False)
    op.create_table('purchase_order',
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=True),
    sa.Column('number', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('issued_by', sa.String(length=36), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','ISSUED','CLOSED','CANCELLED')"),
    sa.ForeignKeyConstraint(['issued_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['purchase_request.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index(op.f('ix_purchase_order_project_id'), 'purchase_order', ['project_id'], unique=False)
    op.create_table('stock_movement',
    sa.Column('balance_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('source_key', sa.String(length=150), nullable=False),
    sa.Column('confirmed_by', sa.String(length=36), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity <> 0'),
    sa.ForeignKeyConstraint(['balance_id'], ['stock_balance.id'], ),
    sa.ForeignKeyConstraint(['confirmed_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_key')
    )
    op.create_index(op.f('ix_stock_movement_balance_id'), 'stock_movement', ['balance_id'], unique=False)
    op.create_table('change_impact',
    sa.Column('change_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('implemented_by', sa.String(length=36), nullable=True),
    sa.Column('implementation_evidence', sa.Text(), nullable=True),
    sa.Column('rechecked_by', sa.String(length=36), nullable=True),
    sa.Column('recheck_passed', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("action IN ('KEEP','PAUSE','CANCEL','REWORK')"),
    sa.ForeignKeyConstraint(['change_id'], ['business_subject.id'], ),
    sa.ForeignKeyConstraint(['implemented_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['rechecked_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['plan_task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('change_id', 'task_id')
    )
    op.create_index(op.f('ix_change_impact_change_id'), 'change_impact', ['change_id'], unique=False)
    op.create_table('payment_request_detail',
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('stage_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reservation', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.CheckConstraint('amount > 0 AND reservation >= 0 AND reservation <= amount'),
    sa.ForeignKeyConstraint(['stage_id'], ['payment_stage.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['business_subject.id'], ),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_table('purchase_order_line',
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('source_line_id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('agreed_ship_date', sa.Date(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity > 0 AND (unit_price IS NULL OR unit_price >= 0)'),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_order.id'], ),
    sa.ForeignKeyConstraint(['source_line_id'], ['purchase_request_line.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_line_id')
    )
    op.create_index(op.f('ix_purchase_order_line_order_id'), 'purchase_order_line', ['order_id'], unique=False)
    op.create_table('task_dependency',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('prerequisite_id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('task_id <> prerequisite_id'),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['plan_task.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['plan_task.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'prerequisite_id')
    )
    op.create_table('delivery_exception',
    sa.Column('order_line_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('expected_ship_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reported_by', sa.String(length=36), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('closed_by', sa.String(length=36), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('OPEN','CLOSED')"),
    sa.ForeignKeyConstraint(['closed_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['order_line_id'], ['purchase_order_line.id'], ),
    sa.ForeignKeyConstraint(['reported_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_exception_order_line_id'), 'delivery_exception', ['order_line_id'], unique=False)
    op.create_table('supplier_shipment',
    sa.Column('order_line_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('shipped_date', sa.Date(), nullable=False),
    sa.Column('reference', sa.String(length=150), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('confirmed_by', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity > 0'),
    sa.ForeignKeyConstraint(['confirmed_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['order_line_id'], ['purchase_order_line.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_line_id', 'reference')
    )
    op.create_index(op.f('ix_supplier_shipment_order_line_id'), 'supplier_shipment', ['order_line_id'], unique=False)
    op.create_table('goods_receipt',
    sa.Column('shipment_id', sa.String(length=36), nullable=False),
    sa.Column('warehouse_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('reference', sa.String(length=150), nullable=False),
    sa.Column('received_by', sa.String(length=36), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity > 0'),
    sa.ForeignKeyConstraint(['received_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['supplier_shipment.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_id', 'reference')
    )
    op.create_index(op.f('ix_goods_receipt_shipment_id'), 'goods_receipt', ['shipment_id'], unique=False)
    op.create_table('receipt_inspection',
    sa.Column('receipt_id', sa.String(length=36), nullable=False),
    sa.Column('accepted_quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('rejected_quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('inspector_id', sa.String(length=36), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('accepted_quantity >= 0 AND rejected_quantity >= 0'),
    sa.ForeignKeyConstraint(['inspector_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['goods_receipt.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_id')
    )
    op.add_column('approval_instance', sa.Column('subject_id', sa.String(length=36), nullable=True))
    op.alter_column('approval_instance', 'request_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.create_unique_constraint('uq_approval_subject_round', 'approval_instance', ['subject_id', 'revision', 'round_no'])
    op.create_foreign_key('fk_approval_subject', 'approval_instance', 'business_subject', ['subject_id'], ['id'])
    op.create_check_constraint('approval_one_subject','approval_instance', '(request_id IS NULL) <> (subject_id IS NULL)')
    op.execute("""CREATE FUNCTION protect_business_fact() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN RAISE EXCEPTION 'Confirmed business facts are immutable; append a correction record'; END $$""")
    for table in ['payment_confirmation','supplier_shipment','goods_receipt','receipt_inspection','stock_movement']:
        op.execute(f'CREATE TRIGGER immutable_fact BEFORE UPDATE OR DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION protect_business_fact()')
    # ### end Alembic commands ###


def downgrade():
    if op.get_bind().scalar(sa.text('SELECT EXISTS(SELECT 1 FROM business_subject)')):
        raise RuntimeError('Business records exist; use a reviewed forward migration or restore plan')
    for table in ['payment_confirmation','supplier_shipment','goods_receipt','receipt_inspection','stock_movement']:
        op.execute(f'DROP TRIGGER immutable_fact ON {table}')
    op.execute('DROP FUNCTION protect_business_fact()')
    op.drop_constraint('approval_one_subject','approval_instance',type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_approval_subject', 'approval_instance', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('uq_approval_subject_round', 'approval_instance', type_='unique')
    op.alter_column('approval_instance', 'request_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('approval_instance', 'subject_id')
    op.drop_table('receipt_inspection')
    op.drop_index(op.f('ix_goods_receipt_shipment_id'), table_name='goods_receipt')
    op.drop_table('goods_receipt')
    op.drop_index(op.f('ix_supplier_shipment_order_line_id'), table_name='supplier_shipment')
    op.drop_table('supplier_shipment')
    op.drop_index(op.f('ix_delivery_exception_order_line_id'), table_name='delivery_exception')
    op.drop_table('delivery_exception')
    op.drop_table('task_dependency')
    op.drop_index(op.f('ix_purchase_order_line_order_id'), table_name='purchase_order_line')
    op.drop_table('purchase_order_line')
    op.drop_table('payment_request_detail')
    op.drop_index(op.f('ix_change_impact_change_id'), table_name='change_impact')
    op.drop_table('change_impact')
    op.drop_index(op.f('ix_stock_movement_balance_id'), table_name='stock_movement')
    op.drop_table('stock_movement')
    op.drop_index(op.f('ix_purchase_order_project_id'), table_name='purchase_order')
    op.drop_table('purchase_order')
    op.drop_index(op.f('ix_plan_task_plan_id'), table_name='plan_task')
    op.drop_table('plan_task')
    op.drop_table('plan_detail')
    op.drop_table('payment_stage')
    op.drop_index(op.f('ix_payment_confirmation_request_id'), table_name='payment_confirmation')
    op.drop_table('payment_confirmation')
    op.drop_index(op.f('ix_pause_record_project_id'), table_name='pause_record')
    op.drop_table('pause_record')
    op.drop_table('engineering_change_detail')
    op.drop_table('contract_detail')
    op.drop_table('business_decision_detail')
    op.drop_table('stock_balance')
    op.drop_table('risk_policy')
    op.drop_table('risk_analysis_result')
    op.drop_table('project_profile')
    op.drop_table('project_mold')
    op.drop_index(op.f('ix_business_subject_project_id'), table_name='business_subject')
    op.drop_index(op.f('ix_business_subject_kind'), table_name='business_subject')
    op.drop_table('business_subject')
    op.drop_table('warehouse')
    op.drop_table('supplier')
    op.drop_table('mold')
    op.drop_table('customer')
    # ### end Alembic commands ###
