export const initialProduct={
 id:'mold',
 product_name:'MoldPilot',
 display_name:'模具项目智能工作台',
 tagline:'从一个任务开始，让业务能力协同工作。',
 attachment_run:{enabled:true,media_types:['application/pdf','image/png','image/jpeg','application/vnd.openxmlformats-officedocument.wordprocessingml.document']},
 attachment_intent_run:{enabled:true,media_types:['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/vnd.ms-excel','text/csv']},
 attachment_processing:{enabled:true,batch_upload:true,media_types:['application/pdf','image/png','image/jpeg','application/vnd.openxmlformats-officedocument.wordprocessingml.document']},
 workspace_tabs:[
  {key:'documents',name:'文件识别',hint:'查看附件解析进度、OCR结果与二次确认'},
  {key:'approvals',name:'审批材料',hint:'查看待审批事项、节点和依据'},
  {key:'contacts',name:'联络单材料',hint:'查看工程联络单、附件和协作进度'},
 ],
 proposal_presentation:{
  action_prefixes:['登记','确认','准备'],
  action_suffixes:['证据登记','证据'],
  detail_links:{contact:{target:'contacts',receipt_field:'case_id',label:'查看材料'}},
  value_names:{},
 },
}
