<script setup lang="ts">
import {computed,onMounted,ref,watch} from 'vue'
import {api,post} from '../../../api'
import {clean,stateLabels} from '../businessForms'
import {valueText,businessNames,statusName} from '../uiText'
import SchemaFields from '../../../components/SchemaFields.vue'
import BusinessFacts from './BusinessFacts.vue'
import HumanCommand from '../../../components/HumanCommand.vue'
import WorkflowSubmit from './WorkflowSubmit.vue'
const selectedRow=ref<any>(null)
const props=defineProps<{permissions:string[]}>()
const emit=defineEmits<{error:[message:string];approval:[id:string];changed:[]}>()
const catalog=ref<any[]>([]),kind=ref(''),records=ref<any[]>([]),projects=ref<any[]>([]),commands=ref<any[]>([]),options=ref<Record<string,any[]>>({})
const editing=ref(false),detail=ref<any>({}),project=ref(''),category=ref(''),remark=ref(''),busy=ref(false),activeCommand=ref<any>(null)
const spec=computed(()=>catalog.value.find(x=>x.key===kind.value))

async function refresh(){if(!kind.value)return;records.value=await api('/business/subjects?kind='+kind.value)}
async function loadOptions(){const [refs,subjects]=await Promise.allSettled([project.value&&kind.value&&props.permissions.includes(kind.value+'.create')?api('/business/options?kind='+kind.value+'&project_id='+project.value+(category.value?'&category='+category.value:'')):Promise.resolve({}),api('/business/subjects')]);
 options.value=refs.status==='fulfilled'?refs.value:{}
 if(subjects.status==='fulfilled'){const all=subjects.value.filter((r:any)=>!project.value||r.project_id===project.value);options.value.design_id=all.filter((r:any)=>r.kind==='design_route'&&r.status==='EFFECTIVE');options.value.assembly_id=all.filter((r:any)=>r.kind==='assembly_issue'&&r.detail?.execution_status==='DONE');options.value.change_id=all.filter((r:any)=>r.kind==='engineering_change');options.value.original_payment_id=all.flatMap((r:any)=>(r.detail?.payments||[]).filter((p:any)=>Number(p.amount)>0).map((p:any)=>({...p,label:r.number+' / '+p.reference+' / '+p.amount+' '+p.currency})));options.value.source_subject_id=all.map((r:any)=>({...r,label:r.number+' · '+stateLabels[r.status]}));options.value.previous_id=all.filter((r:any)=>['project_plan','plan_change'].includes(r.kind));options.value.stage_id=all.flatMap((r:any)=>(r.detail?.stages||[]).map((st:any)=>({...st,label:r.number+' / '+st.name+' / '+st.amount+' '+st.currency})));options.value.task_id=all.flatMap((r:any)=>(r.detail?.tasks||[]).map((t:any)=>({...t,label:r.number+' / '+t.name})))} }
onMounted(async()=>{try{[catalog.value,projects.value,commands.value]=await Promise.all([api('/business/catalog'),api('/projects'),api('/business/commands')]);catalog.value=catalog.value.filter(s=>props.permissions.some(p=>p.startsWith(s.key+'.')));kind.value=catalog.value[0]?.key||'';await loadOptions();await refresh()}catch(e:any){emit('error',e.message)}})
watch(kind,async()=>{editing.value=false;detail.value={};activeCommand.value=null;try{await refresh();await loadOptions()}catch(e:any){emit('error',e.message)}})
watch([project,category],async()=>{try{await loadOptions()}catch{}})
async function save(){busy.value=true;try{await post('/business/subjects',{kind:kind.value,project_id:project.value,category:category.value||null,remark:remark.value,detail:clean(detail.value)});editing.value=false;detail.value={};await refresh();await loadOptions();emit('changed')}catch(e:any){emit('error',e.message)}finally{busy.value=false}}
function command(key:string,resource:any,context:string){const config=commands.value.find(c=>c.key===key);activeCommand.value={action:key,resourceId:resource.id,schema:config.schema,context}}
async function changed(){await refresh();await loadOptions();emit('changed')}
</script>
<template><div class="section-heading"><div><h2>业务流转</h2><p class="muted">材料、审批决定与实际执行分别记录。</p></div><button v-if="spec&&permissions.includes(kind+'.create')" @click="editing=!editing">新建业务草稿</button></div>
<label>业务类型<select v-model="kind"><option v-for="item in catalog" :key="item.key" :value="item.key">{{businessNames[item.key]||item.name}}</option></select></label>
<form v-if="editing&&spec" class="surface form-stack" @submit.prevent="save"><h3>{{spec.name}}草稿</h3><label>项目<select v-model="project" required><option value="">选择项目</option><option v-for="p in projects" :key="p.id" :value="p.id">{{p.code}} · {{p.name}}</option></select></label><label>责任域<select v-model="category"><option value="">项目业务</option><option value="hardware">五金</option><option value="raw_material">原材</option><option value="outsource">委外</option></select></label><SchemaFields v-model="detail" :schema="spec.schema" :root="spec.schema" :options="options"/><label>申请备注<textarea v-model="remark" rows="3"/></label><div class="actions"><button type="button" @click="editing=false">取消</button><button class="primary" :disabled="busy">保存草稿</button></div></form>

<HumanCommand v-if="activeCommand" :key="activeCommand.action+activeCommand.resourceId" v-bind="activeCommand" :options="options" @error="emit('error',$event)" @changed="changed" @close="activeCommand=null"/>
<article v-for="row in records" :key="row.id" class="surface"><div class="section-heading"><strong>{{row.number}}</strong><span class="status">{{statusName(row.status)}}</span></div><p>{{row.remark}}</p><details><summary>查看完整业务材料</summary><BusinessFacts :value="row.detail"/></details><div class="actions"><button v-if="['DRAFT','REJECTED','RETURNED'].includes(row.status)&&permissions.includes(kind+'.submit')" @click="selectedRow=row">核对并提交审批</button><button v-if="row.status==='APPLY_BLOCKED'&&permissions.includes(kind+'.execute')" @click="command('business.retry_apply',row,row.number)">核对生效条件</button><button v-if="row.kind==='supplier_payment'&&row.status==='EFFECTIVE'&&permissions.includes('finance.confirm')" @click="command('finance.confirm',row,row.number)">登记实际付款</button></div>
<div v-if="row.status==='EFFECTIVE'"><button v-if="row.kind==='assembly_issue'&&permissions.includes('assembly.execute')&&row.detail.execution_status!=='DONE'" @click="command('assembly.execute',row,row.number)">登记装配执行</button><button v-if="row.kind==='trial_request'&&permissions.includes('trial.confirm')&&!row.detail.results?.length" @click="command('trial.confirm',row,row.number)">登记试模结论</button><div v-for="stage in row.detail.stages||[]" :key="stage.id" class="task-row"><span>{{stage.name}} · {{stage.amount}} {{valueText('currency',stage.currency)}} · {{stage.condition_confirmed?'条件已核验':'待核验'}}</span><button v-if="!stage.condition_confirmed&&permissions.includes('finance.condition')" @click="command('finance.condition',stage,row.number+' / '+stage.name)">核验阶段条件</button></div><div v-for="task in row.detail.tasks||[]" :key="task.id" class="task-row"><span>{{task.name}} · {{stateLabels[task.status]}}</span><button v-if="permissions.includes('plan.execute')&&['PLANNED','RUNNING'].includes(task.status)" @click="command('plan.execute',task,row.number+' / '+task.name)">记录实际执行</button></div><div v-for="impact in row.detail.impacts||[]" :key="impact.id" class="task-row"><span>{{valueText('action',impact.action)}} · {{impact.recheck_passed?'复检合格':impact.implemented_by?'待复检':'待实施'}}</span><button v-if="!impact.implemented_by&&permissions.includes('change.implement')" @click="command('change.implement',impact,row.number)">登记实施</button><button v-if="impact.implemented_by&&!impact.recheck_passed&&permissions.includes('change.recheck')" @click="command('change.recheck',impact,row.number)">登记复检</button></div><button v-if="row.kind==='engineering_change'&&permissions.includes('engineering_change.execute')" @click="command('change.close',row,row.number)">核对并关闭工程联络单</button></div>
</article><p v-if="!records.length&&!editing" class="empty">暂无当前权限范围内的业务记录。</p>
<WorkflowSubmit v-if="selectedRow" resource-type="business_subject" :row="selectedRow" @close="selectedRow=null" @error="emit('error',$event)" @submitted="selectedRow=null;changed();emit('approval',$event)"/></template>
