<script setup lang="ts">
import {onMounted,ref,watch} from 'vue'
import {api,post} from '../../../api'
import {valueText,statusName} from '../uiText'
const emit=defineEmits<{error:[message:string]}>();const kind=ref('projects'),records=ref<any[]>([]),users=ref<any[]>([]),customers=ref<any[]>([]),adding=ref(false),form=ref<any>({}),busy=ref(false)
const kinds:Record<string,string>={projects:'项目',customers:'客户',suppliers:'供应商',materials:'料品',warehouses:'仓库',molds:'模具档案'}
async function load(){records.value=await api(kind.value==='projects'?'/projects':'/master/'+kind.value)}
onMounted(async()=>{try{[users.value,customers.value]=await Promise.all([api('/users'),api('/master/customers')]);await load()}catch(e:any){emit('error',e.message)}})
watch(kind,async()=>{adding.value=false;form.value={};try{await load()}catch(e:any){emit('error',e.message)}})
async function save(){busy.value=true;try{await post(kind.value==='projects'?'/projects':'/master/'+kind.value,form.value);adding.value=false;form.value={};await load()}catch(e:any){emit('error',e.message)}finally{busy.value=false}}
</script>
<template><div class="section-heading"><h2>基础业务资料</h2><button @click="adding=!adding">新建资料</button></div><label>资料类型<select v-model="kind"><option v-for="(name,key) in kinds" :key="key" :value="key">{{name}}</option></select></label><form v-if="adding" class="surface form-stack" @submit.prevent="save"><label>稳定编号<input v-model="form.code" required/></label><label>名称<input v-model="form.name" required/></label><label v-if="['suppliers','materials'].includes(kind)">责任域<select v-model="form.category" required><option value="hardware">五金</option><option value="raw_material">原材</option><option value="outsource">委外</option></select></label><label v-if="kind==='materials'">单位<input v-model="form.unit" required/></label><template v-if="kind==='projects'"><label>项目负责人<select v-model="form.owner_user_id" required><option v-for="u in users" :key="u.id" :value="u.id">{{u.display_name}}</option></select></label><label>客户<select v-model="form.customer_id"><option v-for="c in customers" :key="c.id" :value="c.id">{{c.name}}</option></select></label><label>加工方式<select v-model="form.execution_mode"><option value="INTERNAL">内部制造</option><option value="FULL_OUTSOURCE">整套委外</option></select></label></template><p class="muted">创建项目不会自动批准开工；仓库启用须另行确认管理范围。</p><div class="actions"><button type="button" @click="adding=false">取消</button><button class="primary" :disabled="busy">确认保存资料</button></div></form><article v-for="r in records" :key="r.id" class="surface"><h3>{{r.name}}</h3><p class="muted">{{r.code||r.internal_number}} · {{r.category?valueText('category',r.category):r.status?statusName(r.status):''}}</p></article></template>
