<script setup lang="ts">
import {onMounted,ref} from 'vue'
import {api,post,shanghai} from '../../../api'
const props=defineProps<{permissions:string[]}>();const emit=defineEmits<{error:[message:string]}>()
const policy=ref<any>(null),days=ref(3),reason=ref(''),result=ref<any>(null),busy=ref(false)
onMounted(async()=>{try{policy.value=await api('/risk/policy');if(policy.value)days.value=policy.value.near_due_days}catch(e:any){emit('error',e.message)}})
async function save(){busy.value=true;try{policy.value=await post('/risk/policy',{near_due_days:days.value,reason:reason.value});result.value=null}catch(e:any){emit('error',e.message)}finally{busy.value=false}}
async function analyze(){busy.value=true;try{result.value=await post('/risk/analyze')}catch(e:any){emit('error',e.message)}finally{busy.value=false}}
const signals:Record<string,string>={REPORTED_EXCEPTION:'存在上报异常',NEAR_DUE_UNSHIPPED:'临期仍未全部发货',OVERDUE_UNSHIPPED:'已逾期仍未全部发货'}
</script>
<template><h2>供应商发货风险</h2><p class="muted">由你的本次查询触发，只分析授权责任域；不推断整套模具总体延期。</p><form v-if="permissions.includes('risk.configure')" class="surface form-stack" @submit.prevent="save"><h3>临期判断规则</h3><label>约定发货日前多少天计入临期<input v-model.number="days" type="number" min="0" max="90" required/></label><label>配置依据<input v-model="reason" required/></label><button :disabled="busy" class="primary">确认发布规则版本</button></form><p>{{policy?'当前规则第 '+policy.version+' 版'+' · 临期 '+policy.near_due_days+' 天':'规则尚未配置，不能采用默认阈值判断'}}</p><button class="primary" :disabled="!policy||busy" @click="analyze">{{busy?'正在核对业务事实…':'分析当前可见范围'}}</button><section v-if="result"><p class="muted">{{shanghai(result.as_of)}} · 规则第 {{result.rule_version}} 版</p><p v-for="note in result.limitations" :key="note" class="warning">{{note}}</p><article v-for="f in result.data" :key="f.line_id" class="surface"><h3>{{f.supplier}} · {{f.material}}</h3><p>{{f.order_number}} · 约定 {{f.agreed_ship_date}} · 未发 {{f.remaining_quantity}} {{f.unit}}</p><p v-for="s in f.signals" :key="s">{{signals[s]}}</p><p v-for="r in f.exception_reasons" :key="r">{{r}}</p><p class="muted" v-for="s in f.suggestions" :key="s">{{s}}</p></article><p v-if="!result.data.length">本次可见资料中未发现命中规则的记录。</p></section></template>
