"""add quotation rejection table and minor change indicator"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '47cef9904a93'
down_revision = 'f60e6c8a3d48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotation_rejection',
    sa.Column('subject_id', sa.String(), nullable=False),
    sa.Column('quotation_subject_id', sa.String(), nullable=False),
    sa.Column('rejection_category', sa.String(length=30), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=False),
    sa.Column('decision_date', sa.Date(), nullable=False),
    sa.Column('decided_by', sa.String(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default='1', nullable=False),
    sa.CheckConstraint("rejection_category IN ('PRICE_TOO_LOW', 'TIMELINE_IMPOSSIBLE', 'TECHNICAL_DIFFICULTY', 'CAPACITY_SHORTAGE', 'CUSTOMER_CREDIT', 'MATERIAL_SHORTAGE', 'RESOURCE_CONFLICT', 'PROFIT_MARGIN_LOW', 'OTHER')", name='quotation_rejection_category_check'),
    sa.ForeignKeyConstraint(['subject_id'], ['business_subject.id'], name='fk_quotation_rejection_subject'),
    sa.ForeignKeyConstraint(['quotation_subject_id'], ['business_subject.id'], name='fk_quotation_rejection_quotation'),
    sa.ForeignKeyConstraint(['decided_by'], ['app_user.id'], name='fk_quotation_rejection_user'),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_index('ix_quotation_rejection_quotation_subject_id', 'quotation_rejection', ['quotation_subject_id'])

    op.add_column('engineering_change_detail', sa.Column('is_minor_change', sa.Integer(), nullable=False, server_default='0'))
    op.create_check_constraint('engineering_change_is_minor_change', 'engineering_change_detail', 'is_minor_change IN (0, 1)')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('engineering_change_is_minor_change', 'engineering_change_detail', type_='check')
    op.drop_column('engineering_change_detail', 'is_minor_change')
    op.drop_index('ix_quotation_rejection_quotation_subject_id', 'quotation_rejection')
    op.drop_table('quotation_rejection')
    # ### end Alembic commands ###
