"""Design case for approval template selection"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '57b26330cbf2'
down_revision = '98ee06b88b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('design_detail', sa.Column('design_type', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('design_detail', 'design_type')
    # ### end Alembic commands ###
