"""manufacturing price trial and finance correction"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '90eb77d6e8dc'
down_revision = '2892f6fa2482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assembly_detail',
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('design_id', sa.String(length=36), nullable=False),
    sa.Column('supervisor_id', sa.String(length=36), nullable=False),
    sa.Column('prerequisites_evidence', sa.Text(), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=False),
    sa.Column('execution_status', sa.String(length=30), nullable=False),
    sa.CheckConstraint("execution_status IN ('NOT_STARTED','RUNNING','DONE')"),
    sa.ForeignKeyConstraint(['design_id'], ['business_subject.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['business_subject.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_table('assembly_execution',
    sa.Column('assembly_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('actual_date', sa.Date(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('confirmed_by', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("action IN ('START','DONE')"),
    sa.ForeignKeyConstraint(['assembly_id'], ['business_subject.id'], ),
    sa.ForeignKeyConstraint(['confirmed_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assembly_id', 'action')
    )
    op.create_table('design_detail',
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('drawing_revision', sa.String(length=100), nullable=False),
    sa.Column('drawing_evidence', sa.Text(), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['business_subject.id'], ),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_table('price_detail',
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=False),
    sa.Column('quote_evidence', sa.Text(), nullable=False),
    sa.CheckConstraint('unit_price >= 0'),
    sa.CheckConstraint('valid_to >= valid_from'),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['business_subject.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_table('trial_detail',
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('assembly_id', sa.String(length=36), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('acceptance_criteria', sa.Text(), nullable=False),
    sa.Column('responsible_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['assembly_id'], ['business_subject.id'], ),
    sa.ForeignKeyConstraint(['responsible_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['business_subject.id'], ),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_table('trial_result',
    sa.Column('trial_id', sa.String(length=36), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('actual_date', sa.Date(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('findings', sa.Text(), nullable=False),
    sa.Column('change_id', sa.String(length=36), nullable=True),
    sa.Column('confirmed_by', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['change_id'], ['business_subject.id'], ),
    sa.ForeignKeyConstraint(['confirmed_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['trial_id'], ['business_subject.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trial_id')
    )
    op.create_table('design_item',
    sa.Column('design_id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('route', sa.String(length=30), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("route IN ('INTERNAL','PURCHASE','OUTSOURCE')"),
    sa.CheckConstraint('quantity > 0'),
    sa.ForeignKeyConstraint(['design_id'], ['business_subject.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['plan_task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('design_id', 'material_id')
    )
    op.create_index(op.f('ix_design_item_design_id'), 'design_item', ['design_id'], unique=False)
    op.create_table('finance_correction_detail',
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('original_payment_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('reversal_evidence', sa.Text(), nullable=False),
    sa.Column('reversal_date', sa.Date(), nullable=False),
    sa.Column('reversal_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['original_payment_id'], ['payment_confirmation.id'], ),
    sa.ForeignKeyConstraint(['reversal_id'], ['payment_confirmation.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['business_subject.id'], ),
    sa.PrimaryKeyConstraint('subject_id'),
    sa.UniqueConstraint('reversal_id')
    )
    op.create_table('order_price_snapshot',
    sa.Column('line_id', sa.String(length=36), nullable=False),
    sa.Column('price_subject_id', sa.String(length=36), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('selected_by', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['purchase_order_line.id'], ),
    sa.ForeignKeyConstraint(['price_subject_id'], ['business_subject.id'], ),
    sa.ForeignKeyConstraint(['selected_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('line_id')
    )
    for table in ('assembly_execution','trial_result'):
        op.execute(f'CREATE TRIGGER immutable_fact BEFORE UPDATE OR DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION protect_business_fact()')


def downgrade():
    for table in ('assembly_detail','design_detail','price_detail','trial_detail','finance_correction_detail','order_price_snapshot'):
        if op.get_bind().scalar(sa.text(f'SELECT EXISTS(SELECT 1 FROM {table})')):
            raise RuntimeError('Business data exists: use a forward migration instead of a destructive downgrade')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_price_snapshot')
    op.drop_table('finance_correction_detail')
    op.drop_index(op.f('ix_design_item_design_id'), table_name='design_item')
    op.drop_table('design_item')
    op.drop_table('trial_result')
    op.drop_table('trial_detail')
    op.drop_table('price_detail')
    op.drop_table('design_detail')
    op.drop_table('assembly_execution')
    op.drop_table('assembly_detail')
    # ### end Alembic commands ###
