"""ERP adapter identity and operation ledger"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '98ee06b88b0d'
down_revision = 'e72c1dc587a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_identity',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('erp_user_id', sa.String(length=40), nullable=False),
    sa.Column('token_ciphertext', sa.Text(), nullable=True),
    sa.Column('authenticated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('erp_user_id')
    )
    op.create_table('erp_operation',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('intent_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('native_id', sa.String(length=80), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('erp_user_id', sa.String(length=40), nullable=False),
    sa.Column('response', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("state IN ('DISPATCHING','SUCCEEDED','REJECTED','UNKNOWN','OBSERVED_APPLIED')"),
    sa.ForeignKeyConstraint(['intent_id'], ['human_action_intent.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('intent_id')
    )
    op.create_index(op.f('ix_erp_operation_native_id'), 'erp_operation', ['native_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_erp_operation_native_id'), table_name='erp_operation')
    op.drop_table('erp_operation')
    op.drop_table('erp_identity')
    # ### end Alembic commands ###
