"""outbox delivery leases and retry state"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = 'e72c1dc587a7'
down_revision = '90eb77d6e8dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_event', sa.Column('lease_id', sa.String(length=36), nullable=True))
    op.add_column('outbox_event', sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('outbox_event', sa.Column('retry_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('outbox_event', sa.Column('last_error', sa.String(length=80), nullable=True))
    op.add_column('outbox_event', sa.Column('dead_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbox_event', 'dead_at')
    op.drop_column('outbox_event', 'last_error')
    op.drop_column('outbox_event', 'retry_at')
    op.drop_column('outbox_event', 'lease_until')
    op.drop_column('outbox_event', 'lease_id')
    # ### end Alembic commands ###
