<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { api, post } from '../api'
import {permissionName,scopeText,capabilityMeta,capabilityName,groupedCapabilities,categoryNames} from '../uiText'
import OrganizationPanel from './OrganizationPanel.vue'
const emit=defineEmits<{error:[message:string]}>()
const users=ref<any[]>([]),grants=ref<any[]>([]),catalog=ref<any>({permissions:{}}),selected=ref<any>(null),projects=ref<any[]>([])
const assignedCapabilities=ref<any[]>([]),capabilityReason=ref('')
const capabilitySearch=ref(''),capabilityDepartment=ref(''),capabilityType=ref('')
const capabilityDepartments=computed(()=>Array.from(new Map(assignedCapabilities.value.map((item:any)=>{const meta=capabilityMeta(item);return [meta.department,meta.departmentName]})).entries()))
const capabilityTypes=computed(()=>Array.from(new Map(assignedCapabilities.value.map((item:any)=>{const meta=capabilityMeta(item);return [meta.type,meta.typeName]})).entries()))
function capabilityMatches(item:any){
 const meta=capabilityMeta(item),keyword=capabilitySearch.value.trim().toLowerCase()
 if(capabilityDepartment.value&&meta.department!==capabilityDepartment.value)return false
 if(capabilityType.value&&meta.type!==capabilityType.value)return false
 if(!keyword)return true
 return [item.key,capabilityName(item.key),item.description,item.permission,meta.departmentName,meta.typeName].some(value=>String(value||'').toLowerCase().includes(keyword))
}
const filteredAssignedCapabilities=computed(()=>assignedCapabilities.value.filter(capabilityMatches))
const assignedCapabilityGroups=computed(()=>groupedCapabilities(filteredAssignedCapabilities.value))
const adding=ref(false),busy=ref(false),username=ref(''),name=ref(''),department=ref(''),password=ref(''),permission=ref('purchase.read'),scopeProject=ref(''),category=ref('hardware'),all=ref(false),reason=ref(''),effect=ref('ALLOW')
async function load(){ [users.value,catalog.value,projects.value]=await Promise.all([api('/users'),api('/catalog'),api('/projects')]) }
async function choose(user:any){try{selected.value=user;[grants.value,assignedCapabilities.value]=await Promise.all([api(`/users/${user.id}/grants`),api(`/users/${user.id}/capabilities`)])}catch(e:any){emit('error',e.message)}}
async function toggleCapability(item:any){busy.value=true;try{const id=selected.value.id;await post(`/users/${id}/capabilities`,{kind:item.kind,key:item.key,enabled:!item.enabled,reason:capabilityReason.value,expected_security_version:selected.value.security_version});await load();await choose(users.value.find(u=>u.id===id))}catch(e:any){emit('error',e.message)}finally{busy.value=false}}
onMounted(async()=>{try{await load()}catch(e:any){emit('error',e.message)}})
async function create(){busy.value=true;try{await post('/users',{username:username.value,display_name:name.value,department:department.value,password:password.value});password.value='';adding.value=false;await load()}catch(e:any){emit('error',e.message)}finally{busy.value=false}}
async function grant(){busy.value=true;try{const scope:any=(all.value||permission.value==='file.upload')?{all:true}:{project_id:[scopeProject.value]};if(!all.value&&(permission.value.startsWith('purchase.')||permission.value.startsWith('contact.')))scope.category=[category.value];await post(`/users/${selected.value.id}/grants`,{permission:permission.value,effect:effect.value,scope,fields:catalog.value.permissions[permission.value],reason:reason.value,expected_security_version:selected.value.security_version});const id=selected.value.id;await load();await choose(users.value.find(u=>u.id===id))}catch(e:any){emit('error',e.message)}finally{busy.value=false}}
async function revoke(g:any){busy.value=true;try{await api(`/users/${selected.value.id}/grants/${g.id}?expected_security_version=${selected.value.security_version}`,{method:'DELETE'});const id=selected.value.id;await load();await choose(users.value.find(u=>u.id===id))}catch(e:any){emit('error',e.message)}finally{busy.value=false}}
</script>
<template><div class="section-heading"><div><h2>人员与权限</h2><p class="muted">能力按用户配置，岗位名称不限制兼任职责。</p></div><button @click="adding=!adding">创建用户</button></div>
<OrganizationPanel @error="emit('error',$event)" @changed="load();selected=null"/>
<form v-if="adding" @submit.prevent="create" class="surface form-stack"><label>登录名<input v-model="username" required pattern="[a-zA-Z0-9_.-]{3,80}"/></label><label>姓名<input v-model="name" required/></label><label>部门<input v-model="department"/></label><label>初始密码<input v-model="password" type="password" minlength="12" autocomplete="new-password" required/></label><button class="primary" :disabled="busy">创建普通用户</button></form>
<div class="user-list"><button v-for="u in users" :key="u.id" :class="{active:selected?.id===u.id}" @click="choose(u)"><span class="avatar">{{u.display_name[0]}}</span><span>{{u.display_name}}<small>{{u.username}} · {{u.department||'未设置部门'}}</small></span><span v-if="u.super_admin" class="muted">超级管理员</span></button></div>
<section v-if="selected" class="surface form-stack"><h3>{{selected.display_name}}的授权</h3><p v-if="selected.super_admin" class="muted">超级管理员具有全量已实现能力，但仍受业务规则、当前席位与人工确认约束。</p>
<div v-for="g in grants.filter(x=>x.active)" :key="g.id" class="grant-row"><div><strong>{{permissionName(g.permission)}} · {{g.effect==='ALLOW'?'允许':'拒绝'}}</strong><small>{{scopeText(g.scope,projects)}}</small></div><button :disabled="busy" @click="revoke(g)">撤销</button></div>
<form v-if="!selected.super_admin" @submit.prevent="grant" class="form-stack"><h3>增加一项完整授权</h3><label>业务动作<select v-model="permission"><option v-for="(_,key) in catalog.permissions" :key="key" :value="key">{{permissionName(String(key))}}</option></select></label><label>效果<select v-model="effect"><option value="ALLOW">允许</option><option value="DENY">明确拒绝</option></select></label><p v-if="permission==='file.upload'" class="muted">允许向本人会话上传附件；关联联络单仍须另外授予联络单附件权限和数据范围。</p><label v-else class="check-label"><input v-model="all" type="checkbox"/>明确授予全部数据范围</label><template v-if="!all&&permission!=='file.upload'"><label>项目<select v-model="scopeProject" required><option value="" disabled>选择项目</option><option v-for="p in projects" :key="p.id" :value="p.id">{{p.code}}</option></select></label><label v-if="permission.startsWith('purchase.')||permission.startsWith('contact.')">采购责任域<select v-model="category"><option v-for="(label,key) in categoryNames" :key="key" :value="key">{{label}}</option></select></label></template><label>授权原因<input v-model="reason" required/></label><p class="muted">每条授权独立限定动作和范围；新增原材权限不会与另一项目的五金权限交叉扩大。</p><button class="primary" :disabled="busy">确认保存授权</button></form><section v-if="!selected.super_admin" class="form-stack"><h3>工具与技能</h3><p class="muted">能力分配与业务权限取交集。启用工具不会扩大数据范围；停用后，进行中的任务会停止继续使用该能力。</p><label>能力变更原因<input v-model="capabilityReason" placeholder="填写启用或停用原因"/></label><div class="capability-filter"><label>查找能力<input v-model="capabilitySearch" placeholder="输入工具、权限或说明关键词"/></label><label>部门<select v-model="capabilityDepartment"><option value="">全部部门</option><option v-for="[key,name] in capabilityDepartments" :key="key" :value="key">{{name}}</option></select></label><label>类型<select v-model="capabilityType"><option value="">全部类型</option><option v-for="[key,name] in capabilityTypes" :key="key" :value="key">{{name}}</option></select></label></div><div class="capability-groups compact capability-grid"><section v-for="department in assignedCapabilityGroups" :key="department.key" class="capability-department"><h3>{{department.name}}</h3><div v-for="type in department.types" :key="type.key" class="capability-type-block"><div class="capability-type-heading"><strong>{{type.name}}</strong><small class="muted">{{type.items.length}} 项</small></div><div v-for="item in type.items" :key="item.kind+item.key" class="grant-row capability-assignment"><div><strong>{{capabilityName(item.key)}} · {{item.kind==='TOOL'?'工具':'技能'}}</strong><div class="capability-tags"><span>{{capabilityMeta(item).departmentName}}</span><span>{{capabilityMeta(item).typeName}}</span></div><small>{{item.description}}</small><small>{{item.enabled?(item.effective?'已启用 · 当前可用':'已启用 · 缺少业务权限或依赖工具'):'未启用'}}</small></div><button :disabled="busy||!capabilityReason.trim()" @click="toggleCapability(item)">{{item.enabled?'停用':'启用'}}</button></div></div></section></div><p v-if="!filteredAssignedCapabilities.length" class="muted">没有匹配的工具或技能。</p></section></section>
</template>
