<script setup lang="ts">
import {currencyNames,valueText} from '../uiText'
import {onMounted,ref} from 'vue'
import {api} from '../api'
import {stateLabels} from '../businessForms'
import HumanCommand from './HumanCommand.vue'
const props=defineProps<{permissions:string[]}>();const emit=defineEmits<{error:[message:string];changed:[]}>()
const prices=ref<any[]>([])
const rows=ref<any[]>([]),commands=ref<any[]>([]),active=ref<any>(null),editing=ref<any>(null),suppliers=ref<any[]>([]),warehouses=ref<any[]>([]),busy=ref(false)
async function load(){try{[rows.value,commands.value]=await Promise.all([api('/orders'),api('/business/commands')]);if(props.permissions.includes('warehouse.read'))warehouses.value=await api('/master/warehouses')}catch(e:any){emit('error',e.message)}}
onMounted(load)
async function edit(row:any){try{suppliers.value=await api('/master/suppliers?project_id='+row.project_id);prices.value=(await api('/business/subjects?kind=purchase_price')).filter((p:any)=>p.status==='EFFECTIVE'&&p.project_id===row.project_id);editing.value=JSON.parse(JSON.stringify(row))}catch(e:any){emit('error',e.message)}}
async function save(){busy.value=true;try{const row=editing.value;await api('/orders/'+row.id,{method:'PUT',body:JSON.stringify({version:row.version,supplier_id:row.supplier_id,currency:row.currency,lines:row.lines.map((l:any)=>({id:l.id,price_subject_id:l.price_subject_id,unit_price:l.unit_price,agreed_ship_date:l.agreed_ship_date}))})});editing.value=null;await load();emit('changed')}catch(e:any){emit('error',e.message)}finally{busy.value=false}}
function command(action:string,resource:any,label:string){active.value={action,resourceId:resource.id,schema:commands.value.find(c=>c.key===action).schema,context:label,initial:action==='order.issue'?{version:resource.version}:{}}}
</script>
<template><h2>采购执行与供应商交付</h2><p class="muted">申请通过生成执行草稿，正式下单及发货事实须由人员确认。</p>
<form v-if="editing" class="surface form-stack" @submit.prevent="save"><h3>{{editing.number}} · 核对成交方案</h3><label>供应商<select v-model="editing.supplier_id" required><option v-for="s in suppliers" :key="s.id" :value="s.id">{{s.name}}</option></select></label><label>币种<select v-model="editing.currency" required><option v-for="(label,code) in currencyNames" :key="code" :value="code">{{label}}</option></select></label><div v-for="line in editing.lines" :key="line.id" class="form-grid"><strong>{{line.material_name}} · {{line.quantity}} {{line.unit}}</strong><label>已审批价格<select v-model="line.price_subject_id" required @change="line.unit_price=prices.find(p=>p.id===line.price_subject_id)?.detail.unit_price"><option value="">请选择有效审批价格</option><option v-for="p in prices.filter(p=>p.detail.supplier_id===editing.supplier_id&&p.detail.material_id===line.material_id&&p.detail.currency===editing.currency)" :key="p.id" :value="p.id">{{p.number}} · {{p.detail.unit_price}} {{valueText('currency',p.detail.currency)}}</option></select></label><label>单价<input :value="line.unit_price" readonly/></label><label>约定发货日期<input v-model="line.agreed_ship_date" type="date" required/></label></div><div class="actions"><button type="button" @click="editing=null">取消</button><button class="primary" :disabled="busy">保存待确认方案</button></div></form>
<HumanCommand v-if="active" :key="active.action+active.resourceId" v-bind="active" :options="{warehouse_id:warehouses}" @close="active=null" @changed="load" @error="emit('error',$event)"/>
<article v-for="row in rows" :key="row.id" class="surface"><div class="section-heading"><strong>{{row.number}}</strong><span class="status">{{stateLabels[row.status]}}</span></div><div class="actions"><button v-if="row.status==='DRAFT'&&permissions.includes('order.edit')" @click="edit(row)">核对供应商与价格</button><button v-if="row.status==='DRAFT'&&permissions.includes('order.issue')" @click="command('order.issue',row,row.number)">正式下单</button></div><section v-for="line in row.lines" :key="line.id" class="surface"><h3>{{line.material_name}}</h3><p>{{line.quantity}} {{line.unit}} · 约定 {{line.agreed_ship_date}} · 已发 {{line.shipped_quantity}}</p><div v-if="row.status==='ISSUED'" class="actions"><button v-if="permissions.includes('shipment.confirm')" @click="command('shipment.confirm',line,row.number+' / '+line.material_name)">登记发货</button><button v-if="permissions.includes('exception.report')" @click="command('exception.report',line,row.number+' / '+line.material_name)">上报异常</button></div><div v-for="e in line.exceptions" :key="e.id" class="warning"><p>{{e.reason}} · {{e.status==='OPEN'?'处理中':'已关闭'}}</p><button v-if="e.status==='OPEN'&&permissions.includes('exception.close')" @click="command('exception.close',e,row.number)">核对异常关闭</button></div><div v-for="shipment in line.shipments" :key="shipment.id" class="task-row"><span>{{shipment.shipped_date}} · {{shipment.quantity}} {{line.unit}} · {{shipment.reference}}</span><button v-if="permissions.includes('receipt.confirm')" @click="command('receipt.confirm',shipment,row.number+' / '+line.material_name)">登记实收</button></div></section></article><p v-if="!rows.length" class="empty">暂无可见采购执行单。</p></template>
